### ISSUE TITLE
Node + ctypes bindings?

### ISSUE THREAD

**Issue by flagxor** [WebAssembly/interface-types#1]
In a node embedding, in addition to JavaScript types, it would be good to be able to express direct calls to system libraries. The "natural" way to do this with the host bindings proposal would be to add a ctypes library to node with properties that would allow it to be optimized to bare calls.

It looks like there is an early work in progress library:
https://www.npmjs.com/package/ctypes

Some thought should go into how to make this work nicely with host bindings.

**Comment by pchickey** [comment]
Closing as out-of-date: these concepts don't map to the current proposal, which has evolved a lot since this issue was opened.
