### ISSUE TITLE
Video Call: March 26th 2020

### ISSUE THREAD

**Issue by jgravelle-google** [WebAssembly/interface-types#101]
Email jgravelle [ at ] google (dot) com for the meeting link. (Meeting will use Zoom software)

Meeting will start at 12noon PST, and will last one hour (until 1pm PST).

Please suggest agenda items as comments on this issue. If we have no agenda items by 10:30am day-of, we'll cancel.

---

[Notes here](https://docs.google.com/document/d/e/2PACX-1vSuVfcRBWRyDlTbIqcFkSBKqXZ4AXOjzHd98_bY-EkU3Rl7SoaXRbuNMyPyzYakbP3q3ACWcSbLFk2N/pub)

**Comment by jgravelle-google** [comment]
Some agenda items:

* Sharing memory via Interface Types (carryover from https://github.com/WebAssembly/interface-types/issues/98)
* Avoiding memory copies: https://github.com/WebAssembly/interface-types/issues/88

**Comment by redradist** [comment]
Where is the link to the meeting ?

**Comment by jgravelle-google** [comment]
> Where is the link to the meeting ?

Sent to you via email.

For clarity, we're following the conventions of the WebAssembly Community Group's video calls, where the link it's publicly available, but we'll send it to anyone who asks. This raises the activation energy needed to join, so everyone who's on the call is serious enough to have sent an email, even if they're just curious and listening in.

**Comment by jgravelle-google** [comment]
[Notes here](https://docs.google.com/document/d/e/2PACX-1vSuVfcRBWRyDlTbIqcFkSBKqXZ4AXOjzHd98_bY-EkU3Rl7SoaXRbuNMyPyzYakbP3q3ACWcSbLFk2N/pub)
