### ISSUE TITLE
Video Call: May 21st 2020

### ISSUE THREAD

**Issue by jgravelle-google** [WebAssembly/interface-types#115]
Email jgravelle [ at ] google (dot) com for the meeting link. (Meeting will use Zoom software)

Meeting will start at 12noon PST, and will last one hour (until 1pm PST).

Please suggest agenda items as comments on this issue. If we have no agenda items by 10:30am PST day-of, we'll cancel.

**Comment by RossTate** [comment]
I'm guessing you mean PDT?

**Comment by jgravelle-google** [comment]
Probably? I can never remember which one is what time of year. Will fix for the next issue.

Also: canceling due to no agenda posted.
