### ISSUE TITLE
validateUtf8 typo in Explainer example

### ISSUE THREAD

**Issue by benweedon** [WebAssembly/interface-types#121]
In the example detailing how two adapted modules could be merged together by a wasm engine, the `$validateUtf8` function is called twice. However, both times it's called on the same string. I think the second instance should be called on `$valSrc` and `$valLen` rather than `$keySrc` and `$keyLen`.

## Actual
```wasm
...
    let (local $valSrc i32) (local $valLen i32) (result i32 i32)
        (call $validateUtf8 (local.get $keySrc) (local.get $keyLen))
        (call $mem2Malloc (local.get $valLen))
...
```

## Expected
```wasm
...
    let (local $valSrc i32) (local $valLen i32) (result i32 i32)
        (call $validateUtf8 (local.get $valSrc) (local.get $valLen))
        (call $mem2Malloc (local.get $valLen))
...
```

**Comment by fgmccabe** [comment]
Comment is correct.
However, the explainer is in the middle of a significant rewrite that make the issue moot.
