### ISSUE TITLE
why JSON?

### ISSUE THREAD

**Issue by fgmccabe** [WebAssembly/interface-types#19]
Why is JSON called out as a special case in this proposal.
Even if we accepted this, where are all the other types (DOM Element, CSS, ..., URL, ... )?
Editorial: I think that it might be better to see web bindings as a special case of the more general inter-module binding problem.

**Comment by lukewagner** [comment]
Agreed that JSON doesn't belong; a wasm module could just import `JSON.parse`, passing its string argument from linear memory via the (in the current Overview.md parlance) `STRING` binding.

(Overview.md is long overdue for a rewrite/refresh based on the [recent TPAC discussion](https://github.com/WebAssembly/meetings/blob/master/2018/TPAC.md#host-bindings-luke-wagner).  I'm waiting on some discussions to bottom out on how to frame the updated proposal, but plan to do that over the next few months.)

**Comment by pchickey** [comment]
Closing as out-of-date: the proposal no longer makes a special case for JSON.
