### ISSUE TITLE
is host bindings available nowadays?

### ISSUE THREAD

**Issue by juepiezhongren** [WebAssembly/interface-types#20]
question

**Comment by littledan** [comment]
The quick answer is, no, it's not fully defined yet, and definitely not shipping in web browsers.

**Comment by juepiezhongren** [comment]
@littledan i was a bit puzzled that for chrome that there is bug tracking for host binding
https://bugs.chromium.org/p/chromium/issues/detail?id=841496

**Comment by pchickey** [comment]
Closing as out-of-date: the proposal has been largely redesigned, and renamed as interface-types. The proposal is still in its infancy and is not yet available on any platform.
