### ISSUE TITLE
Split `bind`s out into their own subsection?

### ISSUE THREAD

**Issue by fitzgen** [WebAssembly/interface-types#32]
Right now we have two subsections:

1. Web IDL Type Subsection: contains webidl type definitions
2. Web IDL Function Binding Subsection: contains function bindings definitions and `bind`s that pair a bindings definition with an actual wasm function

It seems like it might make sense to split (2) into two subsections: one for the function bindings definitions and another for the `bind` pairings.

**Comment by lukewagner** [comment]
Agreed.  Happy to have a PR; otherwise I'll get around to it before too long.

**Comment by pchickey** [comment]
Closing as out-of-date: the proposal has evolved and no longer has Web IDL types or function bindings.
