### ISSUE TITLE
Make names clearer around function bindings and bind statements

### ISSUE THREAD

**Issue by fitzgen** [WebAssembly/interface-types#33]
I keep wanting to refer to both of them as "bindings" and I think we could wordsmith some better names to make things more clear.

On IRC, @lukewagner suggested 

* "function bindings" -> "coercion functions"
* "bind statement" -> "export binding" or "import binding"

That seems like an improvement to me.

**Comment by Hywan** [comment]
Agree on the suggestion.

**Comment by lukewagner** [comment]
Ok great.  There is probably a big explainer refactoring necessary for ☃ Bindings, so this can be included as something to be fixed.

**Comment by pchickey** [comment]
Closing as out-of-date: the proposal has evolved into Interface Types since this was opened, and these particular names are no longer around.
