### ISSUE TITLE
Any estimate of how long until a browser supports this?

### ISSUE THREAD

**Issue by trusktr** [WebAssembly/interface-types#36]
I'm interested in this feature. If you _had_ to guess, how long would you guess it will take for the first browser to support DOM references inside Wasm?

My guess is 1 to 2 more years. Thoughts?

**Comment by KronicDeth** [comment]
It is on [the agenda for the in-person tomorrow](https://github.com/WebAssembly/meetings/blob/652b823ddb0e1b1caa5e05c84f775037c30291b9/2019/CG-06.md#agenda-items), so more information will be available after that.

**Comment by jgravelle-google** [comment]
Also: depends on what you mean by "DOM references in wasm"

If you want to manipulate the DOM via C++/Rust, embind and wasm-bindgen work today. I'm not actually sure of the mechanism by which embind works, but wasm-bindgen stores JS references in a JS array and accesses them by index, which can be passed across the wasm boundary.

If you want to pass opaque JS references to wasm, the anyref proposal is mostly(fully?) implemented in V8 today behind an experimental flag. [That's currently in Stage 3](https://github.com/WebAssembly/proposals/issues/10), and is also on tomorrow's agenda.

If you want this proposal specifically (benefits of which should include stronger typing and improved performance), I think 1-2 years feels about right? Probably 1 year for the first browser to have support behind a flag, and then another year after that for it to be standardized and available everywhere flagless.

**Comment by pchickey** [comment]
Closing as resolved
