### ISSUE TITLE
How dose the source tuple come from?

### ISSUE THREAD

**Issue by Becavalier** [WebAssembly/interface-types#39]
`(type $AddContactFuncWasm (func (param anyref i32 i32 i32 i32 i32) (result i32)))`

Like above, how can we confirm the types and sequence of the params here? I did not find any explainations in the proposal summary (Explainer.md).

**Comment by lukewagner** [comment]
This wasm signature type would be validated to match the corresponding binding (`$addContactBinding`) during the [validation](https://github.com/WebAssembly/webidl-bindings/blob/master/proposals/webidl-bindings/Explainer.md#validation) of the Web IBL Binding section.

**Comment by pchickey** [comment]
Closing as out-of-date: the proposal has evolved since this issue was filed and no longer involves Web IDL bindings
