### ISSUE TITLE
How Best to Contribute?

### ISSUE THREAD

**Issue by Warfields** [WebAssembly/interface-types#41]
Hello, after [opening an issue](https://github.com/WebAssembly/meetings/issues/429) on the Community Group meetings repo I realised that I'd like to contribute to moving the WebIDL proposal from [phase 2 to phase 3](https://github.com/WebAssembly/meetings/blob/master/process/phases.md#2-proposed-spec-text-available-community--working-group). From my understanding this involves two items. First, one or more prototype implementations, like [Rust IDL](https://github.com/rustwasm/wasm-webidl-bindings) and the [wasm-webidl-polyfill ](https://github.com/jgravelle-google/wasm-webidl-polyfill) prototypes. Secondly, the testing framework.

**Comment by jgravelle-google** [comment]
Nit: we're still phase 1 afaik: https://github.com/WebAssembly/proposals

The other bits that are needed in the fullness of time are:
* spec work, actually ironing out what bits we need to implement
* embedder implementations, so prototypes in v8, spidermonkey, cranelift, etc.
* separately from a test framework, individual test cases, or higher-level use cases
* it's probably also useful to have a non-C-like language implementation, e.g. integration in a functional language of some sort (like Haskell, Scheme, Elm), or a VM-based language (like Java, C#)

**Comment by KronicDeth** [comment]
For Erlang/Elixir, we still need to explore how much of Rust's `wasm-bindgen` we will be able to use directly and how much we need to implement from scratch.  If we end up not using as much `wasm-bindgen` or try to produce bindings that will produce Erlang strings (Elixir charlists) which are linked-lists of code points, then we may be a good test case for functional language implementation.

**Comment by Warfields** [comment]
> Nit: we're still phase 1 afaik: https://github.com/WebAssembly/proposals
> 
> The other bits that are needed in the fullness of time are:
> 
> * spec work, actually ironing out what bits we need to implement
> * embedder implementations, so prototypes in v8, spidermonkey, cranelift, etc.
> * separately from a test framework, individual test cases, or higher-level use cases
> * it's probably also useful to have a non-C-like language implementation, e.g. integration in a functional language of some sort (like Haskell, Scheme, Elm), or a VM-based language (like Java, C#)

Oops, I was reading the threading docs and didn't realize that webIDL was phase 1. Ok, I'll look at a couple of things.

**Comment by pchickey** [comment]
Closing as resolved. Please re-open if you need additional help!
