### ISSUE TITLE
Informal regular video call

### ISSUE THREAD

**Issue by jgravelle-google** [WebAssembly/interface-types#44]
There's enough interest in this, and enough of an open design space that it makes sense to have a venue for regular high-bandwidth conversation.

Sign-up/interest/finding-a-time form: [here](https://docs.google.com/forms/d/e/1FAIpQLSe-w4-QeJgY4msFyyprCdszuZP-im7kIYmLUECONwsV36F1Tw/viewform?usp=sf_link)

---

For cadence, to start I'm thinking weekly.

We should have an agenda before each meeting. As for mechanism I propose copying the CG format and having a doc per meeting, in their own meetings/ folder.

For video call software, I assume Zoom works.

---

Feel free to nitpick the specifics here.

**Comment by jgravelle-google** [comment]
Ok based on the results, it's looking like 10am PDT on Thursdays is best.

For video call software... we should probably do whatever the CG does... Hm.

And I'm thinking that submitting PRs is more noise than would be beneficial for agenda+notes setting. So I'm thinking one Issue per meeting, agenda items can be added in comments.

First meeting not tomorrow, but the week after.

**Comment by pchickey** [comment]
Closing as resolved - Jacob now hosts a bi-weekly call. Issues are posted prior to each meeting to announce it and set the agenda.
