### ISSUE TITLE
Video Call: July 25th 2019

### ISSUE THREAD

**Issue by jgravelle-google** [WebAssembly/interface-types#51]
No registration required. Email jgravelle [ at ] google (dot) com for the meeting link. (Meeting will use Zoom software)

Meeting will start at 12noon PDT, and will last one hour (until 1pm PDT).

---

[Notes here](https://docs.google.com/document/d/1O0vcOL5CyO2Top3uE8i7DKfunpGg0qUh9SB4oIbj4w0/edit?usp=sharing)

**Comment by pchickey** [comment]
Can you post an agenda before the meeting?

**Comment by jgravelle-google** [comment]
I would like people to add items to discuss as comments on these issues. Probably should have written that up ahead of time. For the last meeting I'd introduced the agenda item of naming, and then two more were added at the meeting itself.

I'm torn because on one hand I don't want to impose much process here (i.e. we must have agenda items decided on before a meeting), but on the other we should have some idea of what we're going to discuss.

**Comment by PoignardAzur** [comment]
As far as agenda items, I'd be interested in discussing #50 #51 and [the OCAP bindings proposal](https://github.com/WebAssembly/design/issues/1291).

**Comment by jgravelle-google** [comment]
[Notes here](https://docs.google.com/document/d/1O0vcOL5CyO2Top3uE8i7DKfunpGg0qUh9SB4oIbj4w0/edit?usp=sharing)
