### ISSUE TITLE
Video Call: January 2nd 2020

### ISSUE THREAD

**Issue by jgravelle-google** [WebAssembly/interface-types#91]
No registration required. Email jgravelle [ at ] google (dot) com for the meeting link. (Meeting will use Zoom software)

Meeting will start at 12noon PST, and will last one hour (until 1pm PST).

Please suggest agenda items as comments on this issue. If we have no agenda items by 10:30am day-of, we'll cancel.

**Comment by redradist** [comment]
Consider to discuss https://github.com/WebAssembly/interface-types/issues/88#issue-530573108 suggestion

**Comment by jgravelle-google** [comment]
I predict we will have sparse attendance due to the holidays, but we can discuss it.

Do you have the meeting invite? I don't expect there to be much discussion if not.

**Comment by redradist** [comment]
@jgravelle-google 
> I predict we will have sparse attendance due to the holidays, but we can discuss it.
> 
> Do you have the meeting invite? I don't expect there to be much discussion if not.

No, I do not have an invite ...
