### ISSUE TITLE
Video Call: February 13th 2020

### ISSUE THREAD

**Issue by jgravelle-google** [WebAssembly/interface-types#95]
No registration required. Email jgravelle [ at ] google (dot) com for the meeting link. (Meeting will use Zoom software)

Meeting will start at 12noon PST, and will last one hour (until 1pm PST).

Please suggest agenda items as comments on this issue. If we have no agenda items by 10:30am day-of, we'll cancel.

**Comment by ajklein** [comment]
Not exactly an agenda item, but should we cancel this meeting since we'll already be discussing Interface Types today in the full CG meeting?

**Comment by jgravelle-google** [comment]
sounds good to me
