### ISSUE TITLE
Video Call: March 12th 2020

### ISSUE THREAD

**Issue by jgravelle-google** [WebAssembly/interface-types#98]
Email jgravelle [ at ] google (dot) com for the meeting link. (Meeting will use Zoom software)

Meeting will start at 12noon PST, and will last one hour (until 1pm PST).

Please suggest agenda items as comments on this issue. If we have no agenda items by 10:30am day-of, we'll cancel.

**Comment by fgmccabe** [comment]
Suggestion from Alon: sharing memory through interface types for performance critical applications.

**Comment by jgravelle-google** [comment]
Talked to @fgmccabe, we have a scheduling conflict for our only agenda item, so let's postpone that discussion until next time. Sorry for the short notice
